# Generated by Django 4.2.5 on 2023-10-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_celular',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('PEP', 'PEP')], max_length=20),
        ),
    ]
