# Generated by Django 4.2.5 on 2023-10-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_alter_programa_nombre_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='observaciones',
            field=models.TextField(max_length=300),
        ),
    ]
