# Generated by Django 4.2.5 on 2023-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_alter_novedad_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.CharField(choices=[('Asiste', 'Asiste'), ('Falla', 'Falla'), ('Retardo', 'Retardo'), ('Novedad', 'Novedad')], default=False, max_length=45),
        ),
    ]
