# Generated by Django 4.2.5 on 2023-11-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_alter_asistencia_fecha_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_asistencia',
            field=models.DateField(),
        ),
    ]
