# Generated by Django 4.2.3 on 2023-08-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='horario_id',
        ),
        migrations.AddField(
            model_name='instructor',
            name='registro_asistencia',
            field=models.ManyToManyField(blank=True, to='asistencia.asistencia'),
        ),
    ]
