# Generated by Django 4.2.3 on 2023-07-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_novedad_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='instructor_ficha',
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_ficha',
            field=models.ManyToManyField(related_name='instructores', to='asistencia.ficha'),
        ),
    ]
