# Generated by Django 4.2.3 on 2023-07-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_remove_ficha_instructor_ficha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructor_ficha',
        ),
        migrations.AddField(
            model_name='ficha',
            name='instructor_ficha',
            field=models.ManyToManyField(to='asistencia.instructor'),
        ),
    ]
