# Generated by Django 4.2.3 on 2023-07-31 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_remove_instructor_instructor_ficha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='instructor_ficha',
            new_name='instructores',
        ),
    ]
