# Generated by Django 4.2.5 on 2023-10-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
