# Generated by Django 4.2.5 on 2023-10-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('APRENDIZ', 'Aprendiz'), ('INSTRUCTOR', 'Instructor')], max_length=45),
        ),
    ]
